package docs

import (
	"image/png"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDOCX_BuildAndParse(t *testing.T) {
	tmpDir := t.TempDir()
	docxPath := filepath.Join(tmpDir, "test.docx")

	mdInput := `# Project Documentation

## Overview
This is a test document generated by **AgentDoc** CLI.

- Feature 1: Fast Concurrency
- Feature 2: Surgical Line Editing

| Key | Value |
| API | Active |
| Version | 1.0.0 |

Final paragraph.
`

	// 1. Build DOCX
	if err := MarkdownToDOCX(mdInput, docxPath); err != nil {
		t.Fatalf("MarkdownToDOCX failed: %v", err)
	}

	// Verify file was created
	stat, err := os.Stat(docxPath)
	if err != nil || stat.Size() == 0 {
		t.Fatalf("docx file not created or empty: %v", err)
	}

	// 2. Parse back to Markdown
	parsedMD, err := DOCXToMarkdown(docxPath)
	if err != nil {
		t.Fatalf("DOCXToMarkdown failed: %v", err)
	}
	if !strings.Contains(parsedMD, "Project Documentation") {
		t.Errorf("expected heading in parsed markdown: %s", parsedMD)
	}
	if !strings.Contains(parsedMD, "AgentDoc") {
		t.Errorf("expected text in parsed markdown: %s", parsedMD)
	}

	// 3. Inspect
	info, err := InspectDOCX(docxPath)
	if err != nil {
		t.Fatalf("InspectDOCX failed: %v", err)
	}
	if info.WordCount == 0 {
		t.Errorf("expected non-zero word count: %+v", info)
	}

	// 4. Edit: Replace text
	editedDocx := filepath.Join(tmpDir, "edited.docx")
	if err := ReplaceTextInDOCX(docxPath, editedDocx, "AgentDoc", "DeepMindAgent"); err != nil {
		t.Fatalf("ReplaceTextInDOCX failed: %v", err)
	}
	editedMD, _ := DOCXToMarkdown(editedDocx)
	if !strings.Contains(editedMD, "DeepMindAgent") {
		t.Errorf("replacement not found in edited docx: %s", editedMD)
	}

	// 5. Append paragraph
	appendedDocx := filepath.Join(tmpDir, "appended.docx")
	if err := AppendParagraphToDOCX(editedDocx, appendedDocx, "Appended Section", 2); err != nil {
		t.Fatalf("AppendParagraphToDOCX failed: %v", err)
	}
	appendedMD, _ := DOCXToMarkdown(appendedDocx)
	if !strings.Contains(appendedMD, "Appended Section") {
		t.Errorf("appended paragraph not found: %s", appendedMD)
	}

	// 6. Snapshot to PNG
	pngPath := filepath.Join(tmpDir, "snapshot.png")
	if err := SnapshotDOCX(appendedDocx, pngPath); err != nil {
		t.Fatalf("SnapshotDOCX failed: %v", err)
	}
	pngFile, err := os.Open(pngPath)
	if err != nil {
		t.Fatalf("failed opening snapshot png: %v", err)
	}
	defer pngFile.Close()

	img, err := png.Decode(pngFile)
	if err != nil {
		t.Fatalf("snapshot is not a valid png: %v", err)
	}
	if img.Bounds().Dx() != 800 || img.Bounds().Dy() != 1100 {
		t.Errorf("unexpected image dimensions: %v", img.Bounds())
	}
}
